"""srsRAN 4G configuration file generator."""
from __future__ import annotations
import os
import secrets
from typing import Any


def generate_sim_for_tower(tower: dict[str, Any]) -> dict[str, Any]:
    """Auto-generate a SIM profile matched to a tower (same MCC/MNC/carrier)."""
    import uuid
    mcc = tower["mcc"]
    mnc = tower["mnc"]
    # IMSI = MCC + MNC + random 9 digits
    suffix = str(secrets.randbelow(10**9)).zfill(9)
    imsi = f"{mcc}{mnc}{suffix}"
    ki  = secrets.token_hex(16).upper()
    opc = secrets.token_hex(16).upper()
    apn_map = {"410": "broadband", "012": "vzwinternet", "480": "vzwinternet",
               "260": "fast.t-mobile.com"}
    apn = apn_map.get(mnc, "internet")
    return {
        "id":      f"SIM-{str(uuid.uuid4())[:8].upper()}",
        "name":    f"{tower['carrier']} — {tower['city']} ({tower['id']})",
        "carrier": tower["carrier"],
        "imsi":    imsi,
        "imei":    str(353490069000000 + secrets.randbelow(999999)),
        "ki":      ki,
        "opc":     opc,
        "amf":     "8000",
        "sqn":     "000000000001",
        "mcc":     mcc,
        "mnc":     mnc,
        "apn":     apn,
        "mode":    "soft",
        "_tower_id": tower["id"],
    }


def generate_enb_conf(tower: dict[str, Any]) -> str:
    """Generate enb.conf for a given tower profile."""
    return f"""\
#####################################################################
#                   srsENB configuration file
# Generated by srsRAN Manager
# Tower: {tower['name']}  ({tower['city']}, {tower.get('state','')})
# Carrier: {tower['carrier']}  MCC:{tower['mcc']} MNC:{tower['mnc']}
#####################################################################

[enb]
enb_id = {tower['enb_id']:#010x}
mcc = {tower['mcc']}
mnc = {tower['mnc']}
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
s1c_bind_port = 0
n_prb = {tower['n_prb']}
#tm = 4
#nof_ports = 2

[enb_files]
sib_config = sib.conf
rr_config  = rr.conf
rb_config  = rb.conf

[rf]
dl_earfcn = {tower['dl_earfcn']}
tx_gain = {tower['tx_power']}
rx_gain = 40

#device_name = default
#device_args = auto
#time_adv_nsamples = auto

[scheduler]
policy = time_rr
policy_args = 2

[sl]

[pcap]
enable = none
mac_filename = /tmp/enb_mac.pcap
mac_nr_filename = /tmp/enb_mac_nr.pcap
s1ap_filename = /tmp/enb_s1ap.pcap

[log]
all_level = warning
all_hex_limit = 32
filename = /tmp/enb.log
file_max_size = -1

[gui]
enable = false
"""


def generate_rr_conf(tower: dict[str, Any]) -> str:
    """Generate rr.conf (radio resources) for a tower."""
    # Derive UL EARFCN offset by band
    ul_offset = {
        4: 18000 - 1575,   # band 4: DL 1475-1575, UL 18000-18100 (offset 18000)
        12: 23010 - 5010,  # band 12: DL 5010-5179, UL 23010-23179
        13: 23180 - 5180,  # band 13: DL 5180-5279, UL 23180-23279
        17: 23730 - 5730,  # band 17: DL 5730-5849, UL 23730-23849
        2: 18600 - 600,    # band 2:  DL 600-1199,  UL 18600-19199
        5: 20312 - 128,    # band 5:  DL 128-251,   UL 20312-20435
    }
    band = tower['band']
    dl_earfcn = tower['dl_earfcn']
    ul_earfcn = dl_earfcn + ul_offset.get(band, 18000)

    return f"""\
// Radio resources config — generated by srsRAN Manager
// Tower: {tower['name']}
// Band {band}  DL EARFCN {dl_earfcn}  PCI {tower['pci']}

cell_list =
(
  {{
    // RF config
    rf_port = 0;
    cell_id = {tower['cell_id']:#04x};
    tac = {tower['tac']:#06x};
    pci = {tower['pci']};
    //root_seq_idx = 204;
    dl_earfcn = {dl_earfcn};
    //ul_earfcn = {ul_earfcn};
    ho_active = false;

    // Optional 5G NSA config
    nr_cell_list = ();

    // Carrier aggregation SCells (empty = no CA)
    scell_list = ();
  }}
);

// Mobility config
meas_cell_list =
(
);

meas_report_desc =
(
);
"""


def generate_sib_conf(tower: dict[str, Any]) -> str:
    """Generate sib.conf (System Information Blocks) for a tower."""
    band = tower['band']
    dl_earfcn = tower['dl_earfcn']

    # Band-specific frequency info
    freq_table = {
        2:  {"arfcn_offset": 600, "dl_carrier_freq": 1930000, "ul_carrier_freq": 1850000},
        4:  {"arfcn_offset": 1475, "dl_carrier_freq": 2110000, "ul_carrier_freq": 1710000},
        5:  {"arfcn_offset": 128,  "dl_carrier_freq": 869000,  "ul_carrier_freq": 824000},
        12: {"arfcn_offset": 5010, "dl_carrier_freq": 729000,  "ul_carrier_freq": 699000},
        13: {"arfcn_offset": 5180, "dl_carrier_freq": 746000,  "ul_carrier_freq": 777000},
        17: {"arfcn_offset": 5730, "dl_carrier_freq": 734000,  "ul_carrier_freq": 704000},
    }
    fi = freq_table.get(band, freq_table[12])

    nrb_map = {6: 1, 15: 2, 25: 3, 50: 4, 75: 5, 100: 6}
    n_prb = tower['n_prb']
    dl_bw = nrb_map.get(n_prb, 4)  # default 50 PRB → enum 4

    return f"""\
// SIB config — generated by srsRAN Manager
// Tower: {tower['name']}

sib1 =
{{
  intra_freq_reselection = "Allowed";
  q_rx_lev_min = -70;
  //p_max = 23;
  cell_barred = "NotBarred";
  si_window_length = 20;
  sched_info_list = (
  {{
    si_periodicity = 16;
    sib_mapping_info = (
      {{entry_tag = "sib2";}},
      {{entry_tag = "sib3";}}
    );
  }},
  {{
    si_periodicity = 32;
    sib_mapping_info = (
      {{entry_tag = "sib4";}},
      {{entry_tag = "sib5";}}
    );
  }},
  {{
    si_periodicity = 64;
    sib_mapping_info = (
      {{entry_tag = "sib13";}}
    );
  }}
  );
  system_info_value_tag = 0;
}};

sib2 =
{{
  rr_config_common_sib =
  {{
    rach_cnfg =
    {{
      num_ra_preambles = 52;
      preamble_init_rx_target_pwr = -104;
      pwr_ramping_step = 6;
      preamble_trans_max = 10;
      ra_resp_win_size = 10;
      mac_con_res_timer = 64;
      max_harq_msg3_tx = 4;
    }};
    bcch_cnfg =
    {{
      modification_period_coeff = 2;
    }};
    pcch_cnfg =
    {{
      default_paging_cycle = 32;
      nB = "1";
    }};
    prach_cnfg =
    {{
      root_sequence_index = 128;
      prach_cnfg_info =
      {{
        high_speed_flag = false;
        zero_correlation_zone_config = 0;
        prach_freq_offset = 2;
        prach_config_index = 4;
      }};
    }};
    pdsch_cnfg =
    {{
      rs_power = -6;
      p_b = 1;
    }};
    pusch_cnfg =
    {{
      n_sb = 1;
      hopping_mode = "inter-subframe";
      pusch_hopping_offset = 4;
      enable_64_qam = false;
      ul_rs =
      {{
        cyclic_shift = 0;
        group_assignment_pusch = 0;
        group_hopping_enabled = false;
        sequence_hopping_enabled = false;
      }};
    }};
    pucch_cnfg =
    {{
      delta_pucch_shift = 2;
      n_rb_cqi = 2;
      n_cs_an = 0;
      n1_pucch_an = 12;
    }};
    ul_pwr_ctrl =
    {{
      p0_nominal_pusch = -85;
      alpha = "1.0";
      p0_nominal_pucch = -107;
      delta_flist_pucch =
      {{
        format_1  = 0;
        format_1b = 3;
        format_2  = 1;
        format_2a = 2;
        format_2b = 2;
      }};
      delta_preamble_msg3 = 6;
    }};
    ul_cp_length = "len1";
  }};
  ue_timers_and_constants =
  {{
    t300 = 2000;
    t301 = 100;
    t310 = 200;
    n310 = 1;
    t311 = 10000;
    n311 = 1;
  }};
  freq_info =
  {{
    ul_carrier_freq_present = true;
    ul_bw_present = true;
    additional_spectrum_emission = 1;
    ul_carrier_freq = {fi['ul_carrier_freq']};
    ul_bw = {dl_bw};
  }};
  mbsfn_subfr_cnfg_list_present = false;
  time_alignment_timer = "infinity";
}};

sib3 =
{{
  cell_reselection_common =
  {{
    q_hyst = 2;
  }};
  cell_reselection_serving =
  {{
    s_non_intra_search = 5;
    thresh_serving_low = 7;
    cell_resel_prio = 6;
  }};
  intra_freq_cell_resel_info =
  {{
    q_rx_lev_min = -61;
    p_max = 23;
    s_intra_search = 5;
    presence_ant_port_1 = true;
    neigh_cell_cnfg = 1;
    t_resel_eutra = 1;
  }};
}};

sib4 =
{{
}};

sib5 =
{{
}};

sib6 =
{{
}};

sib7 =
{{
}};

sib9 =
{{
  hnb_name = "{tower['carrier']}-{tower['city']}-{tower['id']}";
}};

sib13 =
{{
  mbsfn_area_info_list_r9 =
  (
    {{
      mbsfn_area_id_r9 = 1;
      non_mbsfn_region_length = "s2";
      notification_indicator_r9 = 0;
      mcch_related_bcch_info_r9 =
      {{
        mcch_repetition_period_r9 = "rf32";
        mcch_offset_r9 = 0;
        mcch_modification_period_r9 = "rf512";
        sf_alloc_info_r9 = "10000000";
        signalling_mcs_r9 = "n7";
      }};
    }}
  );
  notification_config =
  {{
    notification_repeat_coeff_r9 = "n2";
    notification_offset_r9 = 0;
    notification_sf_index_r9 = 1;
  }};
}};
"""


def generate_ue_conf(sim: dict[str, Any], tower: dict[str, Any] | None = None) -> str:
    """Generate ue.conf for a SIM profile, optionally locked to a tower."""
    earfcn_line = ""
    if tower:
        earfcn_line = f"dl_earfcn = {tower['dl_earfcn']}"

    if sim['mode'] == 'pcsc':
        usim_section = """\
[usim]
mode = pcsc
#reader =
#pin  = 1234
"""
    else:
        usim_section = f"""\
[usim]
mode = soft
algo = milenage
opc  = {sim['opc']}
k    = {sim['ki']}
imsi = {sim['imsi']}
imei = {sim['imei']}
"""

    tower_comment = ""
    if tower:
        tower_comment = f"# Locked to tower: {tower['name']} ({tower['city']})\n"

    return f"""\
#####################################################################
#                   srsUE configuration file
# Generated by srsRAN Manager
# SIM Profile: {sim['name']}
# Carrier: {sim['carrier']}  MCC:{sim.get('mcc','')} MNC:{sim.get('mnc','')}
{tower_comment}#####################################################################

[rf]
{f'dl_earfcn = {tower["dl_earfcn"]}' if tower else '#dl_earfcn = 3400'}
freq_offset = 0
tx_gain = 80
rx_gain = 40
#srate = 23.04e6
#nof_antennas = 1

#device_name = default
#device_args = auto
#time_adv_nsamples = auto
#burst_preamble_us = 0

[rat.eutra]
dl_earfcn = {tower['dl_earfcn'] if tower else 3400}
nof_carriers = 1

{usim_section}
[rrc]
ue_category = 4
#release        = 8
#feature_group  = 0xe6041000
#mbms_service_id = -1
#mbms_service_port = 4321

[nas]
apn = {sim.get('apn', 'internet')}
#apn_protocol = ipv4
#user =
#pass =
#force_imsi_attach = false

[gw]
netns = ue1
#ip_devname = tun_srsue
#ip_netmask = 255.255.255.0

[gui]
enable = false

[log]
all_level = warning
all_hex_limit = 32
filename = /tmp/ue.log
file_max_size = -1

[pcap]
enable = none
mac_filename = /tmp/ue_mac.pcap
mac_nr_filename = /tmp/ue_mac_nr.pcap
"""


def generate_epc_conf(tower: dict[str, Any]) -> str:
    """Generate epc.conf (srsEPC) matched to a tower."""
    return f"""\
#####################################################################
#                   srsEPC configuration file
# Generated by srsRAN Manager
# Tower: {tower['name']}  MCC:{tower['mcc']} MNC:{tower['mnc']}
#####################################################################

[mme]
mme_code = 0x1a
mme_group = 0x0001
tac = {tower['tac']}
mcc = {tower['mcc']}
mnc = {tower['mnc']}
mme_bind_addr = 127.0.1.100
apn = {_apn_for_mnc(tower['mnc'])}
dns_addr = 8.8.8.8
encryption_algo = EEA0
integrity_algo = EIA1
paging_timer = 2

[hss]
db_file = /tmp/srsran_user_db.csv

[spgw]
gtpu_bind_addr = 127.0.1.1
sgi_if_addr = 176.16.0.1
sgi_if_name = srs_spgw_sgi
max_paging_queue = 100

[log]
all_level = warning
filename = /tmp/epc.log
"""


def _apn_for_mnc(mnc: str) -> str:
    return {"410": "broadband", "012": "vzwinternet", "480": "vzwinternet",
            "260": "fast.t-mobile.com"}.get(mnc, "internet")


def generate_user_db(sim: dict[str, Any]) -> str:
    """Generate user_db.csv for srsEPC HSS with this SIM subscriber.

    Format: name,auth_algo,imsi,k,op_type,op,amf,sqn,qci,ip_alloc
    srsRAN uses 'mil' for Milenage, not 'milenage'.
    """
    name = sim.get("id", "ue1").replace(",", "_")
    return (
        "#\n"
        "# .csv to store UE's information in HSS\n"
        "# Kept in the following format: \"Name,Auth,IMSI,Key,OP_Type,OP/OPc,AMF,SQN,QCI,IP_alloc\"\n"
        "#\n"
        f"{name},mil,"
        f"{sim['imsi']},"
        f"{sim['ki'].lower()},"
        f"opc,"
        f"{sim['opc'].lower()},"
        f"{sim['amf']},"
        f"{sim['sqn']},"
        f"7,dynamic\n"
    )


def export_tower_configs(tower: dict[str, Any], output_dir: str) -> list[str]:
    """Write all 3 eNB config files for a tower to output_dir. Returns list of paths."""
    os.makedirs(output_dir, exist_ok=True)
    files = {
        "enb.conf": generate_enb_conf(tower),
        "rr.conf":  generate_rr_conf(tower),
        "sib.conf": generate_sib_conf(tower),
    }
    written = []
    for fname, content in files.items():
        path = os.path.join(output_dir, fname)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        written.append(path)
    return written


def export_ue_conf(sim: dict[str, Any], tower: dict[str, Any] | None,
                   output_dir: str) -> str:
    """Write ue.conf for a SIM profile to output_dir. Returns path."""
    os.makedirs(output_dir, exist_ok=True)
    content = generate_ue_conf(sim, tower)
    path = os.path.join(output_dir, "ue.conf")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    return path


def export_full_bundle(tower: dict[str, Any], sim: dict[str, Any],
                       output_dir: str) -> list[str]:
    """Export complete srsRAN bundle: enb+rr+sib+epc+user_db+ue configs."""
    os.makedirs(output_dir, exist_ok=True)
    files = {
        "enb.conf":          generate_enb_conf(tower),
        "rr.conf":           generate_rr_conf(tower),
        "sib.conf":          generate_sib_conf(tower),
        "epc.conf":          generate_epc_conf(tower),
        "user_db.csv":       generate_user_db(sim),
        "ue.conf":           generate_ue_conf(sim, tower),
    }
    written = []
    for fname, content in files.items():
        path = os.path.join(output_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    return written
